name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  # sdk: ^3.2.6 # switching bounds for null safety
  sdk: ^2.12.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  dart_console:
  http: ^1.2.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
